[package]
name = "cex"
version = "0.3.0-alpha"
authors = ["oooutlk <oooutlk@outlook.com>"]
license = "MIT"
keywords = [ "exception", "error", "throw", "throws", "ad-hoc" ]
readme = "README.md"
repository = "https://github.com/oooutlk/enumx"
documentation = "https://docs.rs/cex"
categories = [ "rust-patterns" ]
edition = "2018"
description = "Checked exception in Rust."

[dependencies]
enumx = "^0.3.0-alpha"

[dev-dependencies]
enumx_derive = "^0.3.0-alpha"
cex_derive = "^0.3.0-alpha"
